version: '3.3'

services:
  app:
    container_name: 'Procurmate_Backend'
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "9000:9000"
    volumes:
     - .:/app
